// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sgr.EntityFrameworkCore;

#nullable disable

namespace Sgr.Database.Tool.Migrations
{
    [DbContext(typeof(SgrDbContext))]
    partial class SgrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sgr.OrganizationAggregate.Organization", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("sgr_id")
                        .HasComment("主键");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("m_address")
                        .HasComment("所在地址");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("m_areacode")
                        .HasComment("所属行政区划编码");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("m_code")
                        .HasComment("组织机构编码");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sgr_creationtime")
                        .HasComment("创建时间");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("sgr_creatoruserid")
                        .HasComment("创建的用户ID");

                    b.Property<long>("DeleterUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("sgr_deleteruserid")
                        .HasComment("删除的用户ID");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sgr_deletiontime")
                        .HasComment("删除时间");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("m_email")
                        .HasComment("联系邮箱");

                    b.Property<string>("ExtensionData")
                        .HasMaxLength(2047)
                        .HasColumnType("varchar(2047)")
                        .HasColumnName("sgr_extensiondata")
                        .HasComment("扩展对象/实体");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("sgr_isdeleted")
                        .HasComment("是否已经被软删除");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sgr_lastmodificationtime")
                        .HasComment("修改时间");

                    b.Property<long>("LastModifierUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("sgr_lastmodifieruserid")
                        .HasComment("修改的用户ID");

                    b.Property<string>("Leader")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("m_leader")
                        .HasComment("机构负责人");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("m_logourl")
                        .HasComment("Logo地址");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("m_name")
                        .HasComment("组织机构名称");

                    b.Property<string>("NodePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sgr_nodepath")
                        .HasComment("树节点层次目录");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int")
                        .HasColumnName("m_ordernumber")
                        .HasComment("组织机构排序号");

                    b.Property<string>("OrgTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("m_orgtypecode")
                        .HasComment("组织机构类型编码");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("sgr_parentid")
                        .HasComment("上级节点Id");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("m_phone")
                        .HasComment("联系电话");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("sgr_rowversion")
                        .HasComment("行版本");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("m_state")
                        .HasComment("组织机构状态");

                    b.HasKey("Id");

                    b.ToTable("sgr_organization", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
